services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - /app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:5173"
    working_dir: /app/frontend
    command: npm run dev
    volumes:
      - /app/frontend
      - /app/frontend/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
